include:
  - project: cloudnative/gitlab/gitlabci/terraform
    ref: v2.X
    file: .module.terraform.gitlab-ci.yml
  - project: cloudnative/gitlab/gitlabci/prometheus-testing-ci
    ref: v1.X
    file: .prometheus.gitlab-ci.yml

stages:
  - validate
  - test 
  - standardize style
